### ISSUE TITLE
#US 21 Compartir un link para redes sociales y servicio de mensajeria

### ISSUE THREAD

**Issue by javigoall** [Claudio-Olivera/ProyectoGrupal-ISPC#30]
Como usuario, quiero poder compartir en las redes sociales o mediante servicios de mensajería (whatsapp/ fb messenger/Telegram) un link para que otras personas puedan: 
-ver mi búsqueda
-compartir también ese link en sus redes o por mensajería
-que quienes esten interesados, ingresando a ese link puedan ingresar a la pagina Cuidapets, generar un usuario y postularse.

**Comment by SoledadPeralta** [comment]
Se puede describir en la tarjeta de presentación de cada cuidador
