### ISSUE TITLE
#Tk08 Distinción especial para cuidadores ad honorem

### ISSUE THREAD

**Issue by javigoall** [Claudio-Olivera/ProyectoGrupal-ISPC#33]
Como usuario quiero una distinción especial o un identificatorio para los cuidadores que trabajen ad honorem con Ong´s u entidades relacionadas al proteccionismo, ayuda animal, etc.

**Comment by SoledadPeralta** [comment]
Cómo se podria implementar algo como esto? Cómo podriamos validar que un cuidador cae dentro de esta categoria? La idea esta buena pero me parece dificil de implementar, necesitariamos algo externo al sistema que se comporte como organismo validador o de control..... o ser capaces de recibir algun tipo de certificado de los cuidadores, que podamos evaluar, y entender que son genuinos... etc etc etc. Está dificil esto.

**Comment by javigoall** [comment]
Hay muchas maneras de implementarlo. Una muy sencilla es pedir que la organización emita un simple certificado donde diga que la persona colabora ahí, nos la adjuntan, la validamos y le asignamos dicha insignia.

**Comment by SoledadPeralta** [comment]
Por el momento no se trabajará
