### ISSUE TITLE
#Tk 09 Seccion especial para paseadores de perros en grupo

### ISSUE THREAD

**Issue by javigoall** [Claudio-Olivera/ProyectoGrupal-ISPC#34]
Como usuario quiero una sección especial para paseadores de perro en grupo. Discriminados por zona, horarios y días.

**Comment by SoledadPeralta** [comment]
Esto seria un tipo de prestacion de servicio mas.

**Comment by javigoall** [comment]
Es un servicio aparte que cuidapets puede agregar a futuro quizás. Una sección diferente porque aquí seria un cuidado por horas pero basado en el paseo del perro solamente. Quizás agregar la opción paseo individual o en grupo. Podría ser que el dueño del perro utilice este servicio para ver como se relaciona el canino con el cuidador, su trato, y luego de eso decidir si lo contrata para cuidado por dias etc.

**Comment by SoledadPeralta** [comment]
No se implementará por el momento
