### ISSUE TITLE
#Tk10 Alimento balanceado Incluido en el servicio

### ISSUE THREAD

**Issue by javigoall** [Claudio-Olivera/ProyectoGrupal-ISPC#35]
Como usuario, quiero tener la opcion de ofrecer el servicio de cuidador, con alimento incluido, indicando marca, y precio por kilo.

**Comment by SoledadPeralta** [comment]
Cuidado con alimento incluido, quedaria dentro de los tipos de servicio prestados. La marca del alimento, podria ser una descripcion dentro del perfil del cuidador. El precio afectara simplemente el costo del servicio ofrecido.

**Comment by SoledadPeralta** [comment]
Servicio que se detallaría en la descripción que ingresa cada cuidador al registrarse
